version: "2"

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - unused
    - ineffassign
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - misspell

formatters:
  enable:
    - gofmt
    - goimports
